version: '2'
services:
  haproxy:
    build: ./loadbalancer
    links:
      - server1
      - server2
      - server3
    ports:
      - "1936:1936"
      - "5000:80"
  server1:
    build: ./server
    ports:
      - "5001:5000"
  server2:
    build: ./server
    ports:
      - "5002:5000"
  server3:
    build: ./server
    ports:
      - "5003:5000"
